
# Wallets
dotenv: .env
wallets:
  from_keys: ${PRIVATE_KEY}

# Dependancies
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
# Network connections
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1FA494EC906CE90E9F37563A8AF630E'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  alchemy_rinkeby:
    eth_usd_price_feed: '0x8A753747A1FA494EC906CE90E9F37563A8AF630E'
    verify: True
  ganache-local:
    verify: False
  development:
    verify: False